### PR TITLE
fix(comparator): ensure hash change only shows when all sizes unchanged

### LINKED ISSUE #178: Sometimes the markdown table does not show hash changes when the web UI does
# Problem

Sometimes, the _unexpected hash change_ does not show up in the Markdown table, but it does show up in the web UI.

**Steps to Reproduce:**

If one of the delta sizes are zero, but not all, and the filename's hash changes.

**Expected Result**

They are expected to have the same behavior

**Actual Result**

The web UI shows a hash icon, but the markdown table will not

### PR DESCRIPTION
**Pull request by paularmstrong**
# Problem

There is a discrepency between when the _unexpected hash change_ icon #️⃣is shown in markdown (from comparator) vs the web UI.

# Solution

The web UI had different logic in that it showed the icon if-and-only-if the _current_ size delta is 0, but not if one of the other size keys had a delta. for example, it would show if the gzip size is unchanged, but the stat size has changed. This is incorrect, because we would actually expect the hash to change in that case.

This adds a getter to the `ArtifactDelta` object as a source of truth to know if the hash change was unexpected. This removes the need for duplicative logic in a few places.

Fixes #178 

# TODO

- [ ] 🤓 Add & update tests (always try to _increase_ test coverage)
- [ ] 🔬 Ensure CI is passing (`yarn lint:ci`, `yarn test`, `yarn tsc:ci`)
- [ ] 📖 Update relevant documentation

### CODE REVIEW

File: src/comparator/src/index.ts [hunk 1]
```diff
@@ -493,11 +494,7 @@ export default class BuildComparator {
           memo.push(formatBudgetResult(budget, row[0].text, useEmoji));
         });
 
-        if (
-          cell.failingBudgets.length === 0 &&
-          cell.hashChanged &&
-          Object.values(cell.sizes).every(size => size === 0)
-        ) {
+        if (cell.failingBudgets.length === 0 && cell.hashChangeUnexpected) {
```
Comment (paularmstrong) [inline src/comparator/src/index.ts]: could remove `cell.failingBudgets.length` check

File: src/comparator/src/ArtifactDelta.ts [hunk 2]
```diff
@@ -57,6 +57,14 @@ export default class ArtifactDelta {
     return this._hashChanged;
   }
 
+  public get hashChangeUnexpected(): boolean {
+    return (
+      this._hashChanged &&
+      this.failingBudgets.length === 0 &&
```
Comment (OliverJAsh) [inline src/comparator/src/ArtifactDelta.ts]: I'm curious why we need to check for this (no failing budgets). Surely budgets are an orthogonal concern? Whether or not we have a failing budget, the hash change may have changed unexpectedly.

File: src/comparator/src/ArtifactDelta.ts [hunk 3]
```diff
@@ -57,6 +57,14 @@ export default class ArtifactDelta {
...
+      Object.keys(this.sizes).every(sizeKey => this.sizes[sizeKey] === 0)
```
Comment (OliverJAsh) [inline src/comparator/src/ArtifactDelta.ts]: I guess there's a small chance this could flag some false positives, where the contents changed and therefore the hash changed, but the size (coincidentally) stayed exactly the same. It's a bit of an edge case, but if we did want to fix it, we could do something like

```ts
const providedHashHasChanged = prevProvidedHash !== providedHash;
const calculatedHashHasChanged = calculateHashFromContents(prevContent) !== calculateHashFromContents(content);
const hashChangedUnexpected = providedHashHasChanged && (calculatedHashHasChanged === false);
```

(where "provided hash" is the one returned by the user's `getFilenameHash`)

File: src/comparator/src/ArtifactDelta.ts (hunk 2 above)
Comment (paularmstrong) [reply src/comparator/src/ArtifactDelta.ts]: This was pulled from previous logic in which we prefer a budget failure over a hash change. I think you're right that it's an orthogonal concern and could be pulled out — just need to make sure that everywhere it's displayed, the budget failures are shown as a priority

File: src/comparator/src/ArtifactDelta.ts (hunk 3 above)
Comment (paularmstrong) [reply src/comparator/src/ArtifactDelta.ts]: We don't store the calculated hash if a hash is provided. I am afraid this also overcomplicates things a bit and am hesitant to go down this road.
